/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-06-30 01:16:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/index.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/reset.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/index_%20responsive.css\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/scss/global.css\">\r\n");
      out.write("\r\n");
      out.write("\t<title>아바</title>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<script src=\"/js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("\t<script src=\"/js/jquery-ui.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("<!-- 헤드부분 -->\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<a href=\"/\" class=\"logo\">\r\n");
      out.write("\t\t\t<img src=\"/img/aboutus_logo.png\" alt=\"로고\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<div class=\"login\">\r\n");
      out.write("\t\t\t<a href=\"login.html\" class=\"nav\">로그인 &middot; 회원가입</a>\r\n");
      out.write("\t\t\t<!--<div class=\"name-box\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">김다언 님 ▼</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">계약완료신고</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">쪽지보내기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">로그아웃 →</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>-->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t<li class=\"menu01\"><a href=\"#\">매물찾기</a>\r\n");
      out.write("\t\t\t\t<ul class=\"sub\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">원룸</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">투&middot;쓰리룸</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">오피스텔</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">아파트</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">분양권</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">주택</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">상가</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">사무실</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">토지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">공장</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">건물</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">재개발</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li><a href=\"index.html\">회사소개</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"notice.html\">공지사항</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 메인이미지 -->\r\n");
      out.write("\t<section id=\"main_img\">\r\n");
      out.write("\t\t<div class=\"txt-box\">\r\n");
      out.write("\t\t\t<h3>\r\n");
      out.write("\t\t\t공인중개사의 발품이 되어<br>\r\n");
      out.write("\t\t\t편리함을 더하다\r\n");
      out.write("\t\t\t</h3>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t발로 뛰는 건 우리가 하고 손을 쓰는 건 공인중개사님이 하세요\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 회사소개 -->\r\n");
      out.write("\t<section id=\"contents01\">\r\n");
      out.write("\t\t<article class=\"txt_box\">\r\n");
      out.write("\t\t\t<h3>WHO WE ARE</h3>\r\n");
      out.write("\t\t\t<div class=\"box_in\">\r\n");
      out.write("\t\t\t\t<img src=\"/img/aboutus_con1_img.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t<p>온라인 부동산시장에서 임대인의 부동산 매물정보를 정확하고 신속하게<br>\r\n");
      out.write("\t파악하여 중개인분들에게 전달하며 부동산 계약성사률을 높여드리겠습니다\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article class=\"bg-img\">\r\n");
      out.write("\t\t\t<img src=\"/img/aboutus_con1.png\" alt=\"bg\">\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 회사연혁 -->\r\n");
      out.write("\t<section id=\"history\">\r\n");
      out.write("\t\t<article class=\"in\">\r\n");
      out.write("\t\t\t<h3>OUR HISTORY</h3>\r\n");
      out.write("\t\t\t<img src=\"/img/company_history.png\" alt=\"\" class=\"graph\">\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article class=\"txt\">\r\n");
      out.write("\t\t\t<div class=\"txt01\">\r\n");
      out.write("\t\t\t\t<h4>2017.02</h4>\r\n");
      out.write("\t\t\t\t<p>주식회사 아바 법인설립</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"txt02\">\r\n");
      out.write("\t\t\t\t<h4>2017.09</h4>\r\n");
      out.write("\t\t\t\t<p>아바시스템 중개인 Web오픈</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"txt03\">\r\n");
      out.write("\t\t\t\t<h4>2018.03</h4>\r\n");
      out.write("\t\t\t\t<p>아바시스템 일반인 Web오픈</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 아바서비스 -->\r\n");
      out.write("\t<section id=\"service\">\r\n");
      out.write("\t\t<article class=\"service_in\">\r\n");
      out.write("\t\t\t<h3>OUR SERVICE</h3>\r\n");
      out.write("\t\t\t<img src=\"/img/ourservice.png\" alt=\"\">\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t<article class=\"in_txt\">\r\n");
      out.write("\t\t\t<div class=\"txt01\">\r\n");
      out.write("\t\t\t\t<h5>No Work</h5>\r\n");
      out.write("\t\t\t\t<p>당신이 원하는 매물을 찾기 위해 걷는 거리 매월 30km<br>\r\n");
      out.write("\t\t\t\tABA를 이용하기 위한 거리 40cm</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"txt02\">\r\n");
      out.write("\t\t\t\t<h5>Too Fast</h5>\r\n");
      out.write("\t\t\t\t<p>굳어버린 매물정보, 빠르게 흘러가는<br>\r\n");
      out.write("\t\t\t\t매물정보 어떤 것을 선택하시겠습니까?</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"txt03\">\r\n");
      out.write("\t\t\t\t<h5>So Cheap</h5>\r\n");
      out.write("\t\t\t\t<p>매달 변동하는 매물 확보, 확인에 소모되는 자금을 버리고<br>\r\n");
      out.write("\t\t\t\t저렴한 비용의 ABA를 선택하십시오</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- contact -->\r\n");
      out.write("\t<section id=\"contact\">\r\n");
      out.write("\t\t<article class=\"contact_in\">\r\n");
      out.write("\t\t\t<header class=\"head\">\r\n");
      out.write("\t\t\t\tCONTACT\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<!-- 아바 회사 정보 -->\r\n");
      out.write("\t\t\t<section class=\"info-box\">\r\n");
      out.write("\t\t\t\t<article class=\"text-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box01\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/img/contact_line.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<h5>주소</h5>\r\n");
      out.write("\t\t\t\t\t\t<p>경상남도 진주시 충무공동 87-23 드림it밸리 B동 807호</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"box02\">\r\n");
      out.write("\t\t\t\t\t\t부동산 매물 공실 관리 문의 및 상담\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"box03\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>TEL</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>055.748.9220</p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>FAX</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>055.748.9221</p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>E-mail</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>abasystem2017@gmail.com</p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t<!-- 아바 회사 지도 이미지 -->\r\n");
      out.write("\t\t\t\t<article class=\"map\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/img/contact_map.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</article>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 하단부분 -->\r\n");
      out.write("\t<section id=\"footer\"></section>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t/* 매물 서브메뉴 */\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\".sub\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".menu01\").mouseenter(function(){\r\n");
      out.write("\t\t\t$(this).find(\".sub\").slideDown(1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".menu01\").mouseleave(function(){\r\n");
      out.write("\t\t\t$(\".sub\").slideUp();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\".sub\").hide();\r\n");
      out.write("\t\t$(\".menu01 > li\").mouseover(function(){\r\n");
      out.write("\t\t\t$(this).addClass(\"on\");\r\n");
      out.write("\t\t\t//$(this).find(\".sub\").show();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".menu01 > li\").mouseout(function(){\r\n");
      out.write("\t\t\t$(this).removeClass(\"on\");\r\n");
      out.write("\t\t\t//$(\".sub_mn\").hide();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
